### PR TITLE
Upgraded @angular and rxjs to >=6.0.0. Added takeUntil() to subscriptions.

### PR DESCRIPTION
**Pull request by Domratchev**

### CODE REVIEW

**Review by ebrehault — APPROVED** [review]

**Comment by ebrehault** [comment]
Hi @Domratchev, thank you for contributing!
Your PR looks good to me, I have just noticed the build is broken because of the browserslist queries (see https://travis-ci.org/onna/ngx-speech/builds/433619559?utm_source=github_status&utm_medium=notification).

I am not familiar with browserslist syntax, if you think you can fix this build failure, please do, else I guess I am ok to merge it anyway.

**Comment by Domratchev** [comment]
@ebrehault I will have a look

**Comment by Domratchev** [comment]
With the new changes I don't seem to get any build or build:lib errors locally.
I've removed node_modules and installed everything fresh.

**Comment by ebrehault** [comment]
Thanks @Domratchev !
Apparently Travis is still complaining, but that's just because the CLI test command changed a little bit in Angular 7.
I'll fix it.

**Pull request merged**
